export const GET_ALL_POSTS_LOADING = 'GET_ALL_POSTS_LOADING';
export const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
export const GET_ALL_POSTS_ERROR = 'GET_ALL_POSTS_ERROR'

export const ADD_LIST = "ADD_LIST";



export const DELETE_POST = 'DELETE_POST';


// export const DELETE_POST_LOADING = 'DELETE_POST_LOADING';
// export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
// export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';


export const ADD_POST_LOADING = 'ADD_POST_LOADING';
export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'ADD_POST_ERROR';

// export const GET_SINGLE_POST_LOADING = 'GET_SINGLE_POST_LOADING';
// export const GET_SINGLE_POST_SUCCESS = 'GET_SINGLE_POST_SUCCESS';
// export const GET_SINGLE_POST_ERROR = 'GET_SINGLE_POST_ERROR';

// export const EDIT_POST_LOADING = 'EDIT_POST_LOADING';
// export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
// export const EDIT_POST_ERROR = 'EDIT_POST_ERROR';


